---
title: <center>稅務相關信息</center>
output:
  html_document:
    toc: false
    toc_float: 
      collapsed: false
    toc_depth: 2
---
#[IRS信息 (稅務局)](Tax1.html)
板塊結構:

- IRS對於企業的各種稅務信息，包含17項，其中的藍色字體會連接到IRS相關頁面 (網頁或表格)
- 17大項中的一些重要細節
    - 企業結構
    - 小型企業的稅務指南

#[其它來源信息](Tax2.html)
板塊結構:

- 對於個人企業的5大項稅收，來源於IRS和相關權威網站的數據
    - 所得稅 (Corporate income tax rate)
    - 預估稅 (Estimated Tax)
    - 自雇稅 (Self-Employment Tax)
    - 就業稅 (Employment Tax)
    - 工商稅 (Excise Tax, 消费税)
(I) Wikipedia
    1. Taxation in the United States
        - 工资税簡介, Payroll Tax
        - 财产税簡介, Property Tax
        - 销售税簡介, Sale Tax
        - 资产增值税簡介, Capital Gains Tax
        - 所得稅簡介, Income tax
    2. Sales taxes in the United States
        - 各州基礎銷售稅率、最高銷售稅率(表)
        - 加州附近(地圖)
(II) Bankrate網
    1. Income Taxes
        - 不同狀態人群不同收入等級的繳稅比例(表)
(III) Tax Foundation網
    1. Average State Sale Taxes
        - 各州平均銷售稅稅率(地圖), 2018年1月統計
    2. Marginal State Corporate Income Tax
        - 邊際企業所得稅稅率(地圖), 2018年統計
(IV) Patriot Software網
    1. Payroll Blog
        - 所得稅、工資稅信息
(V) WalletHub網
    1. 2018's Property Taxes by State
        - 2018年各州房地產物業稅(表)
        - 2018年各州車輛財產稅(表)
(VI) Nerdwallet
    1. Capital Gains Tax Rates
        - 2018年不同狀態人群的資本利得稅(表)


######<font color="white">Style</font>
<style>
h1 {font-size: 28px; color: black; font-weight: bold;}
h1.title {color: black; background-color: white;}
h2 {font-size: 20px; color: black; font-weight: bold;}
p {font-size: 16px; color: black;}
ol {font-size: 16px; color: black;}
ul {font-size: 16px; color: black;}
</style>